CREATE TABLE WELL (
	WELL_ID INTEGER NOT NULL,
	"START" NUMERIC,
	STOP NUMERIC,
	STEP NUMERIC,
	COMPANY TEXT DEFAULT ('COMPANY'),
	WELL_NAME TEXT DEFAULT ('WELL'),
	FIELD TEXT DEFAULT ('FIELD'),
	LOCATION TEXT DEFAULT ('LOCATION'),
	SERVICE_COMPANY TEXT DEFAULT ('SERVICE COMPANY'),
	DATE TEXT DEFAULT ('DATE'),
	PROVINCE TEXT DEFAULT ('PROVINCE'), 
	CONSTRAINT well_pk PRIMARY KEY (WELL_ID)
);

CREATE TABLE EFF_H (
	WELL_ID INTEGER NOT NULL,
	X NUMERIC NOT NULL,
	Y NUMERIC NOT NULL,
	Z NUMERIC NOT NULL,
	VALUE NUMERIC NOT NULL
);

CREATE TABLE H (
	WELL_ID INTEGER NOT NULL,
	X NUMERIC NOT NULL,
	Y NUMERIC NOT NULL,
	Z NUMERIC NOT NULL,
	VALUE NUMERIC NOT NULL
);

CREATE TABLE GIS_CURVE (
	WELL_ID INTEGER NOT NULL, 
	DEPTH NUMERIC NOT NULL, 
	"VALUE" NUMERIC);

CREATE TABLE WELLTRACK (
	WELL_ID INTEGER NOT NULL,
	X NUMERIC NOT NULL,
	Y NUMERIC NOT NULL,
	Z NUMERIC NOT NULL,
	DEPTH_ABSOLUTE NUMERIC NOT NULL
);